<?php
$path_prefix = "../";
$page_title = "Can Jaw Surgery Improve Facial Appearance? Real Results Explained | Gnathos Facial Surgery";
$page_description = "Yes — jaw surgery (orthognathic surgery) is one of the most transformative cosmetic procedures available. Learn what changes, how much, and what realistic results look like.";
$page_keywords = "can jaw surgery improve facial appearance, jaw surgery before after, orthognathic surgery cosmetic, jaw surgery facial change, jaw surgery aesthetic results";
$canonical_url = "https://gnathosface.com/blogs/can-jaw-surgery-improve-facial-appearance/";
include $path_prefix . 'header-include.php';
include $path_prefix . 'header.php';
?>
<link href="/blogs/blog-style.css" rel="stylesheet">
<main>
<div class="bg-surface-container-low border-b border-surface-container-high py-8"><div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop">
<nav class="flex items-center gap-2 text-sm text-on-surface-variant font-label-md uppercase tracking-wider mb-6">
<a href="../index.php" class="hover:text-primary transition-colors">Home</a><span class="material-symbols-outlined text-[16px]">chevron_right</span>
<a href="index.php" class="hover:text-primary transition-colors">Insights &amp; Blogs</a><span class="material-symbols-outlined text-[16px]">chevron_right</span>
<span class="text-secondary">Cosmetic Surgery</span></nav>
<h1 class="font-display-lg-mobile text-display-lg-mobile md:font-display-lg md:text-display-lg text-primary mb-6 leading-tight max-w-4xl">Can Jaw Surgery Improve Facial Appearance?</h1>
<div class="flex items-center gap-6"><div class="flex items-center gap-3">
<img src="/asset/dr-navatha-mortha-facial.webp" alt="Author" class="w-10 h-10 rounded-full object-cover shadow-sm"/>
<div class="flex flex-col"><span class="text-sm font-semibold text-primary">Dr. Navatha Mortha</span>
<span class="text-xs text-on-surface-variant uppercase tracking-wider">April 20, 2026</span></div></div></div></div></div>
<div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop py-12 md:py-16">
<div class="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
<article class="lg:col-span-8">
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high mb-12">
<img alt="Before and after orthognathic surgery showing improved facial balance" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=jaw-surgery-cosmetic"/></div>
<div class="prose prose-lg prose-headings:font-headline-md prose-headings:text-primary prose-p:font-body-md prose-p:text-on-surface-variant prose-a:text-secondary prose-ul:my-6 prose-li:my-2 prose-p:my-4 prose-headings:mt-10 prose-headings:mb-4 prose-img:my-8 max-w-none">
<p class="text-xl leading-relaxed text-primary/80 font-medium italic mb-8 border-l-4 border-secondary pl-6">Yes — orthognathic (jaw) surgery is one of the most transformative cosmetic procedures in modern surgery. It changes the underlying facial skeleton, which is what gives the face its shape and balance. Patients routinely describe the change as looking "more like themselves, only better" — balanced, defined, and harmonious.</p>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-surface-container-high my-10 not-prose shadow-sm">
<h3 class="font-headline-sm text-[20px] text-primary mb-4 flex items-center gap-2"><span class="material-symbols-outlined text-secondary">format_list_bulleted</span>Table of Contents</h3>
<ul class="space-y-3 font-body-md text-on-surface-variant list-none p-0 m-0">
<li><a href="#quick" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>The Quick Answer</a></li>
<li><a href="#changes" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>What Jaw Surgery Changes</a></li>
<li><a href="#cases" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Case-by-Case Results</a></li>
<li><a href="#realistic" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Setting Realistic Expectations</a></li>
<li><a href="#faq" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Frequently Asked Questions</a></li>
</ul></div>
<h2 id="quick" class="scroll-mt-24">The Quick Answer</h2>
<p>Jaw surgery repositions the bones that form the foundation of the face. By moving them into more balanced, harmonious positions, the entire midface and lower face change shape — often dramatically, but always in proportion. It is not "cosmetic surgery" in the surface-level sense, but the cosmetic result is real and lasting.</p>
<p>The face reads balance long before it reads individual features. A weak chin, a flat midface, or a jaw that sits too far back pulls the whole face out of proportion — and that is exactly what jaw surgery corrects at the root. Because the skeleton dictates where the soft tissue sits, changing the bone changes the lips, the cheeks, the neck, and the profile all at once.</p>
<p>Read our full <a href="what-is-orthognathic-surgery.php" class="font-semibold text-secondary">guide to orthognathic surgery</a> for context, or our detailed walkthrough on <a href="what-is-orthognathic-surgery-purpose-procedure-and-recovery-explained.php" class="font-semibold text-secondary">the purpose, procedure, and recovery</a> if you are new to the topic.</p>
<h2 id="changes" class="scroll-mt-24">What Jaw Surgery Changes</h2>
<p>The face is built on a frame of bone. Soft tissue — skin, fat, muscle — drapes over that frame, and the shape you see in the mirror is a direct result of what is underneath. That is why jaw surgery produces a different kind of result than fillers, skin treatments, or even a chin implant: it changes the frame itself.</p>
<p>A "weak chin" or a "strong chin" is rarely about the chin bone at all. It is usually a jaw-position problem — the lower jaw sits too far back, too far forward, or sits at a wrong angle. Move the jaw correctly, and the chin falls into proportion without ever touching it. The same applies to a flat midface, a long lower face, or a jaw that looks too wide for the rest of the features.</p>
<ul>
<li><strong>Chin projection</strong> — a receding or weak chin becomes balanced as the lower jaw is repositioned</li>
<li><strong>Lower-jaw width and angle</strong> — a too-wide or asymmetric jaw can be refined or narrowed</li>
<li><strong>Midface projection</strong> — a flat or retruded upper jaw is brought forward, opening the midface</li>
<li><strong>Lip support</strong> — fuller, more defined lips as a side-effect of better skeletal support behind them</li>
<li><strong>Nose-lip-chin balance</strong> — the proportions that define facial aesthetics fall into place</li>
<li><strong>Neck-jaw angle</strong> — sharper and more defined, often reducing the "double-chin" look</li>
<li><strong>Cheekbones</strong> — when the upper jaw is moved, the cheek projection changes too</li>
</ul>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10"><img alt="Profile view of patient showing improved jaw projection after orthognathic surgery" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=jaw-profile-balance"/></div>
<p>The <strong>upper jaw (Le Fort I osteotomy)</strong> does far more than move bone forward. When the maxilla is advanced, the base of the nose lifts subtly, the upper lip gains support and roll, the cheek projection improves, and the area under the eyes looks more open and rested. When the maxilla is impacted (pushed upward), a long face shortens, a gummy smile resolves, and the lower face becomes proportionate again.</p>
<p>The <strong>lower jaw (Bilateral Sagittal Split Osteotomy, or BSSO)</strong> controls chin projection, jawline length, and the angle between the jaw and the neck. Advancing the mandible defines a weak chin, sharpens the neck-jaw angle, and gives the lower lip a fuller, more supported look. Setting the mandible back tames an overly prominent chin and creates a softer, more balanced profile. The two jaws are often moved together in a procedure called bimaxillary surgery, which is where the most dramatic — and most natural-looking — results come from.</p>
<h2 id="cases" class="scroll-mt-24">Case-by-Case Results</h2>
<p>The specific change depends on what is being corrected. Each pattern of jaw disharmony has a signature look, and each one responds to surgery in a predictable way:</p>
<ul>
<li><strong>Recessed lower jaw (retrognathia):</strong> bringing the lower jaw forward defines the chin, sharpens the neck, balances the profile, and often improves the airway</li>
<li><strong>Protruding lower jaw (prognathia):</strong> moving the lower jaw back gives a more balanced, less severe profile and softens a heavy lower third</li>
<li><strong>Recessed upper jaw:</strong> moving it forward gives better cheek projection, lip support, and a more open midface</li>
<li><strong>Long face syndrome / gummy smile:</strong> impaction of the upper jaw shortens the face, reduces gum show, and gives a more pleasing proportion</li>
<li><strong>Facial asymmetry:</strong> levelling the jaws creates symmetry that no soft-tissue procedure can match</li>
</ul>
<p>Many of these cases are discussed in detail in our <a href="jaw-surgery-orthognathic-complete-guide-for-patients.php" class="font-semibold text-secondary">complete jaw-surgery guide</a>, and the <a href="causes-of-facial-asymmetry-common-medical-dental-and-structural-reasons.php" class="font-semibold text-secondary">causes of facial asymmetry</a> are worth understanding before planning any correction.</p>
<p><strong>Recessed lower jaw</strong> is one of the most common reasons patients seek jaw surgery. The chin sits back, the neck looks full even in slim patients, the lips don't quite close at rest, and the side profile loses the clean line from chin to throat. Advancing the lower jaw typically 6–10 mm brings the chin forward, defines the neck, gives the lower lip natural support, and balances the entire profile. The change is often the difference between looking tired and looking rested.</p>
<p><strong>Protruding lower jaw</strong> is the opposite pattern and changes the face in a different way. The chin dominates the profile, the lower lip sits ahead of the upper, and the midface can look flat by comparison. Setting the mandible back re-establishes the relationship between upper and lower jaw, lets the upper lip catch up visually, and gives the face a more conventional, balanced look.</p>
<p><strong>Asymmetry correction</strong> is where jaw surgery outperforms every other procedure. A chin that deviates to one side, a smile that slopes, or a jawline that sits unevenly cannot be fixed with fillers or even implants — the bone itself is off. Levelling the jaws into their correct relationship removes the tilt, centres the chin, balances the smile line, and makes the whole face read as symmetrical. For more on this, see our note on <a href="can-braces-fix-an-asymmetrical-jaw.php" class="font-semibold text-secondary">whether braces alone can fix an asymmetric jaw</a>.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10"><img alt="Close-up of lower face and jawline showing refined contour after orthognathic surgery" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=jawline-contour"/></div>
<h2 id="realistic" class="scroll-mt-24">Setting Realistic Expectations</h2>
<p>Jaw surgery improves balance and proportion — not a specific feature to look like someone else. Best results come when the goal is "a more harmonious version of me," not "look like a celebrity." A 3D simulation during planning lets you see your predicted result before the operation. See <a href="role-of-3d-virtual-planning.php" class="font-semibold text-secondary">3D virtual planning</a>.</p>
<p>Recovery is real — most patients need 2–3 weeks off work and 6–12 weeks before seeing the final result. See <a href="recovery-time-after-jaw-surgery-complete-healing-timeline-and-care-tips.php" class="font-semibold text-secondary">the full recovery timeline</a>. Most of the visible swelling settles by week 6, and the final refinement — the last 10–15% — takes 6 to 12 months as the soft tissue fully settles over the new skeleton. That long tail is normal and is part of why patients say their result keeps improving long after the surgery itself.</p>
<h3>What Jaw Surgery Cannot Do</h3>
<p>Jaw surgery is structural, not surface. It will not change skin texture, erase fine wrinkles, tighten loose neck skin, or replace lost volume in the lips or cheeks. Patients in their late 40s and beyond often combine jaw surgery with a <a href="best-facial-cosmetic-surgery-best-procedures-to-improve-your-appearance.php" class="font-semibold text-secondary">complementary facial procedure</a> such as a facelift, blepharoplasty, or fat grafting to address both the framework and the soft tissue at the same time.</p>
<h3>Real Patient Examples</h3>
<p>A 24-year-old woman with a recessive lower jaw came in complaining that her chin "disappeared" in photos and that her neck looked heavy. BSSO advancement of 8 mm gave her a defined chin, a sharp jawline, and a 90-degree neck angle. The change was enough that close friends commented she looked "more confident" without pinpointing the surgery.</p>
<p>A 32-year-old man with a long face and a 6 mm gummy smile had Le Fort I impaction and a small mandibular setback. The face shortened visibly, the gums stopped showing, and the lower third of the face became proportionate to the rest. He reported that people no longer asked if he was "stressed" — the previous strain was actually skeletal strain around the mouth.</p>
<p>A 19-year-old with a chin that deviated 9 mm to the left had a bimaxillary correction. After surgery, the chin sat centred, the smile line levelled, and the cant of the occlusal plane disappeared. Asymmetry of that magnitude cannot be matched by any non-surgical approach.</p>
<p>Choosing the right surgeon for these changes matters. If you are planning a consultation, our guide on <a href="how-to-choose-the-best-maxillofacial-surgeon-in-hyderabad.php" class="font-semibold text-secondary">how to choose the best maxillofacial surgeon in Hyderabad</a> walks through what to look for.</p>
<p>Jaw surgery can also dovetail with treatment for breathing and airway problems. For patients whose jaw position contributes to obstructive sleep apnoea, the same operation that improves appearance often improves the airway. Read more in <a href="can-jaw-surgery-help-with-sleep-apnea.php" class="font-semibold text-secondary">can jaw surgery help with sleep apnoea</a>. And as with any maxillofacial procedure, it is worth understanding the <a href="side-effects-of-maxillofacial-surgery-risks-complications-and-prevention.php" class="font-semibold text-secondary">risks, complications, and prevention</a> before committing.</p>
<div class="my-12 p-8 md:p-10 bg-gradient-to-br from-primary via-primary-container to-primary rounded-2xl border border-primary-fixed/20 text-center not-prose shadow-xl relative overflow-hidden">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.1),transparent_60%)] pointer-events-none"></div>
<span class="material-symbols-outlined text-[40px] text-secondary mb-4 relative z-10">face_retouching_natural</span>
<h3 class="font-headline-sm text-[26px] text-on-primary mb-3 relative z-10">See Your Predicted Result First</h3>
<p class="text-on-primary-container mb-8 relative z-10 max-w-xl mx-auto">3D surgical planning shows you exactly how your face will change before the operation.</p>
<a href="../contact.php" class="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-secondary text-on-secondary font-semibold text-sm uppercase tracking-wider hover:bg-white hover:text-primary transition-all duration-300 relative z-10 shadow-[0_0_20px_rgba(19,104,112,0.4)]">Book a Consultation<span class="material-symbols-outlined text-[18px]">arrow_forward</span></a></div>
<hr class="my-12 border-surface-container-high"/>
<h2 id="faq" class="scroll-mt-24 font-headline-md text-primary mb-6">Frequently Asked Questions</h2>
<div class="not-prose space-y-4 mb-12">
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Will people notice I had jaw surgery?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes, in a positive way. Most people say you look "better" or "more balanced" without being able to pinpoint what changed. Dramatic cases (large underbite or asymmetry corrections) produce obvious changes.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is jaw surgery better than chin surgery alone?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">For a small chin, a chin implant or genioplasty is simpler. For a truly weak or recessed jaw, full jaw surgery gives a more natural, proportional result that no implant can match.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Will I have scars on my face?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">No. The incisions are made inside the mouth. There are no visible scars on the face.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">How long until I see the final result?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Visible improvement at 6 weeks. Final refinement and full resolution of swelling at 6–12 months. The result is permanent.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Does it change my nose too?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Sometimes, subtly. Moving the upper jaw can change the base of the nose slightly, often for the better. See <a href="rhinoplasty-balancing-aesthetics-function.php" class="font-semibold text-secondary">rhinoplasty for balance</a> for cases where the nose itself needs a change.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can jaw surgery make me look younger?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes — better jaw definition, sharper neck angle, and improved midface projection can take years off the appearance. The effect is structural, not just surface.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">What if I don't like the result?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">3D planning minimises this risk. Major revisions are rare. Minor tweaks can be made with orthodontics or small secondary procedures.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is it worth it?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Most patients say yes — it improves function, breathing, confidence, and appearance simultaneously. The transformation is among the most dramatic in all of surgery.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can jaw surgery fix a gummy smile?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes — when the cause is vertical maxillary excess, Le Fort I impaction of the upper jaw shortens the face and reduces gum show at rest and during smiling. The change is structural and permanent, and it also improves lower-face proportion.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can jaw surgery fix a long face?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes. A long lower face is usually caused by a vertically excess maxilla, sometimes combined with a clockwise-rotated mandible. Impacting the upper jaw and rotating the lower jaw shortens the lower third of the face, balances the chin-to-nose distance, and gives a more proportionate look.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can jaw surgery fix a double chin?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Often, yes. A recessed lower jaw or a steep mandibular plane angle makes submental fat look more prominent. Advancing the mandible and improving the neck-jaw angle removes the skeletal cause and sharpens the contour. If there is significant soft-tissue laxity or excess fat, a complementary procedure such as liposuction or a neck lift may be recommended alongside.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Will I look very different after jaw surgery?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">You will look like a more balanced, harmonious version of yourself. Close friends and family will notice something has changed, but most people say you look "better" or "more rested" rather than "different." Patients with severe asymmetry or large underbites see more obvious changes, but the result still looks natural.</p></details>
</div></div>
<div class="bg-surface-container-low p-8 rounded-2xl border border-surface-container-high flex flex-col md:flex-row gap-6 items-center mt-12">
<div class="w-24 h-24 rounded-full overflow-hidden shrink-0 shadow-md"><img alt="Dr. Navatha Mortha" class="w-full h-full object-cover" src="/asset/dr-navatha-mortha-facial.webp"/></div>
<div><h4 class="font-headline-sm text-lg text-primary mb-1">Dr. Navatha Mortha</h4>
<p class="font-label-md text-secondary uppercase tracking-wider mb-3 text-sm">Senior Consultant &amp; Maxillofacial Surgeon</p>
<p class="text-sm text-on-surface-variant m-0 leading-relaxed">Dr. Mortha uses 3D planning to deliver predictable, natural-looking orthognathic results at Gnathos Facial Surgery.</p></div></div>
</article>
<aside class="lg:col-span-4 space-y-12">
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-4">Search Journal</h3>
<div class="relative"><input type="text" placeholder="Search articles..." class="w-full pl-4 pr-10 py-3 rounded-xl border border-surface-container-high bg-surface text-sm focus:outline-none focus:ring-2 focus:ring-secondary focus:border-transparent"/>
<span class="material-symbols-outlined absolute right-3 top-1/2 -translate-y-1/2 text-on-surface-variant">search</span></div></div>
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-4">Categories</h3>
<ul class="space-y-3 font-body-md text-on-surface-variant">
<li class="flex items-center justify-between group cursor-pointer"><a href="#" class="group-hover:text-secondary transition-colors">Cosmetic Surgery</a><span class="text-xs bg-surface-container-low px-2 py-1 rounded">6</span></li>
<li class="flex items-center justify-between group cursor-pointer"><a href="#" class="group-hover:text-secondary transition-colors">Surgical Techniques</a><span class="text-xs bg-surface-container-low px-2 py-1 rounded">12</span></li>
<li class="flex items-center justify-between group cursor-pointer"><a href="#" class="group-hover:text-secondary transition-colors">Patient Guides</a><span class="text-xs bg-surface-container-low px-2 py-1 rounded">8</span></li>
<li class="flex items-center justify-between group cursor-pointer"><a href="#" class="group-hover:text-secondary transition-colors">Technology</a><span class="text-xs bg-surface-container-low px-2 py-1 rounded">5</span></li>
</ul></div>
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-6">Related Articles</h3>
<div class="space-y-6 flex flex-col">
<div class="group cursor-pointer"><a href="what-is-orthognathic-surgery.php" class="block">
<span class="text-xs font-semibold text-secondary uppercase tracking-wider mb-1 block">Surgical Techniques</span>
<h4 class="font-headline-sm text-lg text-primary leading-snug group-hover:text-secondary transition-colors">What Is Orthognathic Surgery?</h4>
</a></div>
<div class="group cursor-pointer"><a href="best-facial-cosmetic-surgery-best-procedures-to-improve-your-appearance.php" class="block">
<span class="text-xs font-semibold text-secondary uppercase tracking-wider mb-1 block">Cosmetic Surgery</span>
<h4 class="font-headline-sm text-lg text-primary leading-snug group-hover:text-secondary transition-colors">Best Facial Cosmetic Surgery Procedures</h4>
</a></div>
</div></div>
<div class="bg-primary text-on-primary p-8 rounded-2xl shadow-lg relative overflow-hidden text-center sticky top-24">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.1),transparent_70%)] pointer-events-none"></div>
<span class="material-symbols-outlined text-[48px] text-secondary mb-4">face_retouching_natural</span>
<h3 class="font-headline-sm text-2xl mb-3">See Your 3D Result</h3>
<p class="text-on-primary-container text-sm mb-6">Book a jaw-surgery consultation in Hyderabad.</p>
<a href="../contact.php" class="inline-block w-full py-3 rounded-xl bg-secondary hover:bg-secondary/90 transition-colors text-on-secondary font-semibold text-sm uppercase tracking-wider">Book Now</a>
</div></aside></div></div>
</main>
<?php
include $path_prefix . 'footer.php';
?>