<?php
$path_prefix = "../";
$page_title = "How to Cure TMJ Permanently: Real Treatments That Last | Gnathos Facial Surgery";
$page_description = "Curing TMJ permanently requires treating the actual cause. Learn the real treatments — from self-care and splints to arthrocentesis, arthroscopy, and open joint surgery.";
$page_keywords = "how to cure TMJ permanently, cure TMJ, permanent TMJ treatment, TMJ surgery cure, TMJ pain gone forever, last TMJ relief";
$canonical_url = "https://gnathosface.com/blogs/how-to-cure-tmj-permanently/";
include $path_prefix . 'header-include.php';
include $path_prefix . 'header.php';
?>
<link href="/blogs/blog-style.css" rel="stylesheet">
<main>
<div class="bg-surface-container-low border-b border-surface-container-high py-8"><div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop">
<nav class="flex items-center gap-2 text-sm text-on-surface-variant font-label-md uppercase tracking-wider mb-6">
<a href="../index.php" class="hover:text-primary transition-colors">Home</a><span class="material-symbols-outlined text-[16px]">chevron_right</span>
<a href="index.php" class="hover:text-primary transition-colors">Insights &amp; Blogs</a><span class="material-symbols-outlined text-[16px]">chevron_right</span>
<span class="text-secondary">Patient Guides</span></nav>
<h1 class="font-display-lg-mobile text-display-lg-mobile md:font-display-lg md:text-display-lg text-primary mb-6 leading-tight max-w-4xl">How to Cure TMJ Permanently</h1>
<div class="flex items-center gap-6"><div class="flex items-center gap-3">
<img src="/asset/dr-navatha-mortha-facial.webp" alt="Author" class="w-10 h-10 rounded-full object-cover shadow-sm"/>
<div class="flex flex-col"><span class="text-sm font-semibold text-primary">Dr. Navatha Mortha</span>
<span class="text-xs text-on-surface-variant uppercase tracking-wider">April 13, 2026</span></div></div></div></div></div>
<div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop py-12 md:py-16">
<div class="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
<article class="lg:col-span-8">
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high mb-12">
<img alt="Long-term TMJ treatment options — from self-care to surgery" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=tmj-cure"/></div>
<div class="prose prose-lg prose-headings:font-headline-md prose-headings:text-primary prose-p:font-body-md prose-p:text-on-surface-variant prose-a:text-secondary prose-ul:my-6 prose-li:my-2 prose-p:my-4 prose-headings:mt-10 prose-headings:mb-4 prose-img:my-8 max-w-none">
<p class="text-xl leading-relaxed text-primary/80 font-medium italic mb-8 border-l-4 border-secondary pl-6">"Permanent" doesn't mean "surgery" — it means treating the actual cause. For most TMJ patients, the right combination of self-care, splints, and conservative therapy gives lasting relief. For others, a minimally invasive joint procedure solves the problem for good.</p>
<p>You can cure TMJ permanently by matching treatment to the underlying cause. Most patients reach long-term relief through a layered conservative plan of self-care, splint therapy, physiotherapy, and stress control within 6 to 12 months. When conservative care falls short, targeted minimally invasive procedures such as arthrocentesis or arthroscopy resolve symptoms in roughly 80–90% of cases. Open surgery and joint replacement remain reserved for structural disease that does not respond elsewhere.</p>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-surface-container-high my-10 not-prose shadow-sm">
<h3 class="font-headline-sm text-[20px] text-primary mb-4 flex items-center gap-2"><span class="material-symbols-outlined text-secondary">format_list_bulleted</span>Table of Contents</h3>
<ul class="space-y-3 font-body-md text-on-surface-variant list-none p-0 m-0">
<li><a href="#start" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Where to Start</a></li>
<li><a href="#conservative" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Conservative Treatments</a></li>
<li><a href="#minimally" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Minimally Invasive Procedures</a></li>
<li><a href="#surgery" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Surgical Options</a></li>
<li><a href="#lifestyle" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Lifestyle for Long-Term Success</a></li>
<li><a href="#faq" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Frequently Asked Questions</a></li>
</ul></div>
<h2 id="start" class="scroll-mt-24">Where to Start</h2>
<p>The first step is always the right diagnosis. TMJ pain has many causes — disc displacement, arthritis, muscle overload, nerve irritation, or a combination of these — and each responds to a different treatment. Without a clear diagnosis you will end up cycling through splints, painkillers, and exercises that miss the actual problem.</p>
<p>A thorough TMJ workup includes a clinical exam of jaw movement and joint sounds, imaging such as a panoramic radiograph or CBCT, and often an MRI to see the disc position. Your clinician should also screen for related issues such as <a href="causes-of-jaw-pain-on-one-side.php" class="font-semibold text-secondary">one-sided jaw pain</a>, tooth grinding, or sleep problems. If you are unsure which specialist to see first, our guide on <a href="what-type-of-doctor-do-i-need-to-see-for-tmj.php" class="font-semibold text-secondary">the right doctor for TMJ</a> walks you through that decision.</p>
<p>You also need to know that "permanent" means two different things in TMJ care. The first is <em>symptom resolution</em> — pain, clicking, and locking settle and stay away. The second is <em>structural cure</em> — the disc, condyle, and joint surfaces return to a healthy state. Most patients only need the first. Structural cure matters when arthritis, deformity, or trauma has changed the joint itself, and that is when <a href="difference-between-a-dentist-and-a-maxillofacial-surgeon.php" class="font-semibold text-secondary">a maxillofacial surgeon's opinion</a> becomes useful.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10"><img alt="Patient receiving a TMJ examination from a maxillofacial specialist" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=tmj-exam"/></div>
<h2 id="conservative" class="scroll-mt-24">Conservative Treatments</h2>
<p>For roughly 70–80% of TMJ patients, a layered conservative plan produces lasting relief. The word "layered" matters: no single fix works in isolation. You stack small changes until the joint stops hurting, then keep those habits long enough for tissues to settle.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">The Conservative Ladder</h3>
<p>Start with rest and load reduction. Eat a soft diet for two to four weeks. Cut out gum, tough meat, ice, and very chewy snacks. Apply moist heat to tight jaw muscles in the morning and a cold pack to a sore joint after activity. These steps alone often drop pain scores by a third within a week.</p>
<p>Add jaw exercises once the acute pain calms. Slow opening and closing, controlled side-to-side motion, and gentle stretching of the masseter and temporalis muscles restore range of motion. Your physiotherapist can teach you a five-minute daily routine that, done consistently, prevents most flare-ups.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Splint Therapy</h3>
<p>A custom occlusal splint — usually worn at night — takes load off the joint and stops your teeth from wearing down under clenching. Two main types exist. A <strong>stabilisation splint</strong> covers all upper teeth and holds the jaw in a relaxed position; this is what most dentists should be using. An <strong>anterior repositioning splint</strong> pulls the lower jaw forward to recapture a displaced disc and is reserved for specific disc displacement cases. Many dentists overuse repositioning splints, and long-term wear of the wrong splint can change your bite. Ask for a stabilisation splint unless your specialist says otherwise.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10"><img alt="Custom-made stabilisation splint used in TMJ therapy" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=tmj-splint"/></div>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Physiotherapy and Jaw Rehab</h3>
<p>Targeted TMJ physiotherapy works. Manual therapy inside the mouth and around the joint releases trigger points in the pterygoid and masseter muscles. Posture correction — particularly of the head, neck, and shoulders — removes a major contributor to jaw overload. Most patients need 6–10 sessions over two to three months.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Medications</h3>
<p>Short courses of NSAIDs such as ibuprofen or naproxen reduce joint inflammation. For muscle spasm, a short course of a muscle relaxant at night helps. For chronic pain that has outlasted the original injury, low-dose tricyclic antidepressants such as amitriptyline 10–25 mg at bedtime improve sleep and dampen nerve-driven pain. Short-term anti-anxiety medication can break the clench-stress-pain cycle when stress is the trigger. None of these are cures on their own — they buy you the comfort you need to do the exercises, wear the splint, and address the underlying cause.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Stress, Sleep, and the Mind-Body Link</h3>
<p>Bruxism, jaw clenching, and daytime tooth contact are almost always stress-driven. Cognitive behavioural therapy, mindfulness, and basic sleep hygiene reduce clenching frequency measurably within six to eight weeks. If your TMJ symptoms worsen during work deadlines or poor sleep, this layer is non-negotiable. Most of the patients we see who "tried everything" simply missed this piece.</p>
<h2 id="minimally" class="scroll-mt-24">Minimally Invasive Procedures</h2>
<p>When three to six months of conservative care does not give lasting relief, the next step is a joint-level procedure. These are day-case, done under local anaesthesia with sedation, and recovery is short.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Arthrocentesis</h3>
<p>Arthrocentesis is a joint washout. Two needles are placed into the upper joint space, the joint is flushed with sterile saline, and inflammatory debris is removed. It works best for "locked" joints — sudden limited opening from disc displacement without reduction — and for painful joints with effusion. Pain relief is often immediate, and mouth opening improves by 8–12 mm on average. Success rates sit between 80 and 90%.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Arthroscopy</h3>
<p>Arthroscopy adds a small camera through a third portal. The surgeon can directly see the joint lining, the disc, and the condyle, then lyse adhesions, debride inflamed tissue, or inject medication at the end of the case. Indications include disc perforation, synovitis, and suspected intra-articular pathology that did not respond to arthrocentesis. Our detailed guide on <a href="evolution-of-tmj-arthroscopy.php" class="font-semibold text-secondary">the evolution of TMJ arthroscopy</a> explains the technique and indications in depth.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Injections</h3>
<p>Three injection options sit between conservative care and surgery. <strong>Corticosteroid</strong> injected into the joint reduces inflammation in arthritic joints and is useful for short-term pain flares. <strong>Hyaluronic acid</strong> lubricates an arthritic joint and improves gliding; the effect typically lasts 6–12 months and can be repeated. <strong>Botulinum toxin</strong> (Botox) into the masseter and temporalis muscles reduces clenching force for three to six months and is particularly helpful for muscle-driven pain, morning headaches, and hypertrophy from chronic grinding. Some patients need one or two cycles before the underlying habit is broken.</p>
<h2 id="surgery" class="scroll-mt-24">Surgical Options</h2>
<p>Open surgery is reserved for structural disease that has not responded to conservative care and minimally invasive procedures. Most TMJ patients never reach this step.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Arthrotomy and Disc Surgery</h3>
<p>Open arthrotomy allows direct access to the joint. The disc can be repositioned and sutured, a perforated disc can be repaired or replaced with a flap, and bony growths or osteophytes can be removed. Indications are narrow: confirmed internal derangement on MRI, failed arthroscopy, and a joint that is mechanically blocked.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Condylectomy</h3>
<p>Condylectomy removes the condylar head when it is hyperactive, deformed, or affected by a tumour such as condylar hyperplasia. It is a specific, planned procedure rather than a generic TMJ surgery.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Total Joint Replacement</h3>
<p>End-stage joint disease — destroyed condyle, fused joint, severe rheumatoid or degenerative arthritis, or failed prior surgery — calls for total joint replacement. Patient-specific custom prostheses designed from a CT scan now give excellent long-term outcomes, with most studies showing 90%+ patient satisfaction at 10 years.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-6 mb-3">Orthognathic Surgery</h3>
<p>If the jaw position itself is overloading the joint — for example, a retrognathic mandible or a significant open bite — orthognathic surgery repositions the jaws and removes the mechanical cause. This is the "cure" for a specific subset of patients whose TMJ symptoms are driven by skeletal deformity. See our guides on <a href="what-is-orthognathic-surgery.php" class="font-semibold text-secondary">what orthognathic surgery is</a>, <a href="can-braces-fix-an-asymmetrical-jaw.php" class="font-semibold text-secondary">whether braces alone can fix an asymmetrical jaw</a>, and <a href="what-is-orthognathic-surgery-purpose-procedure-and-recovery-explained.php" class="font-semibold text-secondary">orthognathic surgery purpose, procedure, and recovery</a>. Risks and how we prevent them are covered in <a href="side-effects-of-maxillofacial-surgery-risks-complications-and-prevention.php" class="font-semibold text-secondary">risks and complications of maxillofacial surgery</a>.</p>
<p>Wisdom teeth and routine dental work are rarely the cause of TMJ pain, but if you are unsure, <a href="can-wisdom-teeth-cause-tmj.php" class="font-semibold text-secondary">can wisdom teeth cause TMJ</a> addresses the question directly. Trauma is another potential driver; <a href="broken-jaw-symptoms.php" class="font-semibold text-secondary">broken jaw symptoms</a> covers what to look for after a facial injury.</p>
<h2 id="lifestyle" class="scroll-mt-24">Lifestyle for Long-Term Success</h2>
<p>Treatment gets you out of pain. Habits keep you out of pain. The patients who stay well long term are the ones who treat lifestyle as part of the prescription, not an optional extra.</p>
<ul>
<li><strong>Wear your splint nightly</strong> as prescribed — every night, not only when symptoms return.</li>
<li><strong>Avoid gum, ice, and very chewy foods</strong> — they overload the joint and masseter.</li>
<li><strong>Stop nail biting, pen chewing, and resting your chin on your hand</strong> — all of them micro-load the joint.</li>
<li><strong>Practise jaw relaxation</strong> — lips together, teeth apart, tongue on the palate. Build a check-in habit during stressful moments.</li>
<li><strong>Fix your workstation</strong> — screen at eye level, shoulders relaxed, head not poking forward. Forward head posture doubles jaw load.</li>
<li><strong>Address stress actively</strong> — therapy, exercise, breathing work, or any reliable outlet. Chronic clenching is a stress symptom.</li>
<li><strong>Keep regular dental check-ups</strong> — your dentist can spot wear patterns and bite changes early.</li>
</ul>
<p>For ongoing symptom relief in between treatments, <a href="how-to-get-rid-of-jaw-pain-on-one-side.php" class="font-semibold text-secondary">how to get rid of jaw pain on one side</a> walks through the practical steps.</p>
<h3 class="font-headline-sm text-[22px] text-primary mt-8 mb-3">Who Gets Permanent Relief</h3>
<p>Patients who reach a permanent cure usually share three things: a clear diagnosis from the start, a layered plan they actually follow through on, and a willingness to address the stress and posture drivers rather than only the symptoms. If your TMJ pain is muscle-driven and you treat the clenching, you stay well. If your pain is disc-driven and you treat the disc — through a splint, arthrocentesis, or arthroscopy — you stay well. If your pain is skeletal, no amount of splint therapy will override the underlying jaw relationship, and orthognathic surgery becomes the structural fix.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10"><img alt="Patient smiling with relaxed jaw after completing TMJ treatment" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=tmj-recovery"/></div>
<div class="my-12 p-8 md:p-10 bg-gradient-to-br from-primary via-primary-container to-primary rounded-2xl border border-primary-fixed/20 text-center not-prose shadow-xl relative overflow-hidden">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.1),transparent_60%)] pointer-events-none"></div>
<span class="material-symbols-outlined text-[40px] text-secondary mb-4 relative z-10">medical_services</span>
<h3 class="font-headline-sm text-[26px] text-on-primary mb-3 relative z-10">Plan for Lasting Relief</h3>
<p class="text-on-primary-container mb-8 relative z-10 max-w-xl mx-auto">Get a definitive diagnosis and a long-term treatment plan in one visit.</p>
<a href="../contact.php" class="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-secondary text-on-secondary font-semibold text-sm uppercase tracking-wider hover:bg-white hover:text-primary transition-all duration-300 relative z-10 shadow-[0_0_20px_rgba(19,104,112,0.4)]">Book a Consultation<span class="material-symbols-outlined text-[18px]">arrow_forward</span></a></div>
<hr class="my-12 border-surface-container-high"/>
<h2 id="faq" class="scroll-mt-24 font-headline-md text-primary mb-6">Frequently Asked Questions</h2>
<div class="not-prose space-y-4 mb-12">
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can TMJ be cured permanently?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes — most patients achieve permanent relief when the underlying cause is identified and treated correctly. Surgery is rarely needed. The exception is end-stage joint disease, where joint replacement is the structural fix.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can TMJ heal on its own?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Mild TMJ symptoms from short-term overload — a week of clenching during a stressful project, for example — can settle with rest and a soft diet. Persistent pain, clicking, locking, or headaches lasting more than a few weeks usually need active treatment.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is TMJ disorder reversible?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Most TMJ disorders are reversible when caught early. Muscle pain, acute disc displacement, and inflammation all settle with the right treatment. Advanced arthritis and severe structural damage are managed rather than reversed, which is why early assessment matters.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">How long does it take for TMJ to heal?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Conservative care shows measurable improvement within 4–6 weeks. Most patients reach a stable result within 6–12 months. Arthrocentesis and arthroscopy improve symptoms within days to weeks. Joint replacement recovery runs 3–6 months for full function.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">How long does TMJ treatment take to work?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Most patients see improvement within 4–6 weeks of starting conservative care. Surgical treatments have varying recovery times, from days (arthrocentesis) to months (joint replacement).</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is surgery the only way to cure TMJ permanently?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></highlighted><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">No. The majority of patients who achieve permanent relief never have surgery. Conservative care and minimally invasive procedures together resolve most TMJ disorders. Open surgery is reserved for structural disease that does not respond elsewhere.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can a mouth guard cure TMJ?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">A custom stabilisation splint cures muscle-driven TMJ pain caused by clenching when worn consistently. It does not fix disc displacement, arthritis, or skeletal causes on its own, and an over-the-counter boil-and-bite guard usually makes symptoms worse.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Will TMJ come back after treatment?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">With proper self-care and a night guard, recurrence is uncommon. Untreated underlying causes (clenching, jaw deformity) can cause symptoms to return.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is TMJ surgery worth it?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">For the right patient, yes. Modern TMJ surgery has high success rates and can transform quality of life. A specialist can tell you if you qualify.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Does TMJ ever go away on its own?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Mild TMJ symptoms may settle with self-care, but persistent pain, clicking, or locking usually needs treatment.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">What is the success rate of TMJ arthrocentesis?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Around 80–90% for pain relief and improved opening. It is often the first-line procedure when conservative care fails.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is jaw realignment surgery needed for TMJ?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Only when the jaw position itself is causing the joint overload. Many TMJ cases don't need jaw surgery. See <a href="can-braces-fix-an-asymmetrical-jaw.php" class="font-semibold text-secondary">braces vs jaw surgery</a>.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Where can I get lasting TMJ treatment in Hyderabad?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Gnathos Facial Surgery offers a full TMJ service from diagnosis to joint replacement. See <a href="how-to-choose-the-best-maxillofacial-surgeon-in-hyderabad.php" class="font-semibold text-secondary">how to choose a surgeon</a>.</p></details>
</div></div>
<div class="bg-surface-container-low p-8 rounded-2xl border border-surface-container-high flex flex-col md:flex-row gap-6 items-center mt-12">
<div class="w-24 h-24 rounded-full overflow-hidden shrink-0 shadow-md"><img alt="Dr. Navatha Mortha" class="w-full h-full object-cover" src="/asset/dr-navatha-mortha-facial.webp"/></div>
<div><h4 class="font-headline-sm text-lg text-primary mb-1">Dr. Navatha Mortha</h4>
<p class="font-label-md text-secondary uppercase tracking-wider mb-3 text-sm">Senior Consultant &amp; Maxillofacial Surgeon</p>
<p class="text-sm text-on-surface-variant m-0 leading-relaxed">Dr. Mortha leads the TMJ service at Gnathos Facial Surgery, providing arthrocentesis, arthroscopy, and joint replacement in Hyderabad.</p></div></div>
</article>
<aside class="lg:col-span-4 space-y-12">
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-4">Search Journal</h3>
<div class="relative"><input type="text" placeholder="Search articles..." class="w-full pl-4 pr-10 py-3 rounded-xl border border-surface-container-high bg-surface text-sm focus:outline-none focus:ring-2 focus:ring-secondary focus:border-transparent"/>
<span class="material-symbols-outlined absolute right-3 top-1/2 -translate-y-1/2 text-on-surface-variant">search</span></div></div>
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-4">Categories</h3>
<ul class="space-y-3 font-body-md text-on-surface-variant">
<li class="flex items-center justify-between group cursor-pointer"><a href="#" class="group-hover:text-secondary transition-colors">Patient Guides</a><span class="text-xs bg-surface-container-low px-2 py-1 rounded">8</span></li>
</ul></div>
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-6">Related Articles</h3>
<div class="space-y-6 flex flex-col">
<div class="group cursor-pointer"><a href="what-is-tmj-disorder.php" class="block">
<span class="text-xs font-semibold text-secondary uppercase tracking-wider mb-1 block">Patient Guides</span>
<h4 class="font-headline-sm text-lg text-primary leading-snug group-hover:text-secondary transition-colors">What Is TMJ Disorder?</h4>
</a></div>
<div class="group cursor-pointer"><a href="evolution-of-tmj-arthroscopy.php" class="block">
<span class="text-xs font-semibold text-secondary uppercase tracking-wider mb-1 block">Surgical Techniques</span>
<h4 class="font-headline-sm text-lg text-primary leading-snug group-hover:text-secondary transition-colors">The Evolution of TMJ Arthroscopy</h4>
</a></div>
</div></div>
<div class="bg-primary text-on-primary p-8 rounded-2xl shadow-lg relative overflow-hidden text-center sticky top-24">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.1),transparent_70%)] pointer-events-none"></div>
<span class="material-symbols-outlined text-[48px] text-secondary mb-4">medical_services</span>
<h3 class="font-headline-sm text-2xl mb-3">Plan for a Cure</h3>
<p class="text-on-primary-container text-sm mb-6">Specialist TMJ evaluation in Hyderabad.</p>
<a href="../contact.php" class="inline-block w-full py-3 rounded-xl bg-secondary hover:bg-secondary/90 transition-colors text-on-secondary font-semibold text-sm uppercase tracking-wider">Book Now</a>
</div></aside></div></div>
</main>
<?php
include $path_prefix . 'footer.php';
?>