<?php
$path_prefix = "../";
$page_title = "What Is TMJ Disorder? Causes, Symptoms &amp; Treatment | Gnathos Facial Surgery";
$page_description = "TMJ disorder affects the jaw joint and the muscles that control it. Learn the causes, the symptoms, and the full range of treatments — from self-care to surgery.";
$page_keywords = "what is TMJ disorder, TMJ disorder symptoms, TMJ causes, TMJ treatment, temporomandibular joint disorder, jaw joint pain";
$canonical_url = "https://gnathosface.com/blogs/what-is-tmj-disorder/";
include $path_prefix . 'header-include.php';
include $path_prefix . 'header.php';
?>
<link href="blog-style.css" rel="stylesheet">
<main>
<div class="bg-surface-container-low border-b border-surface-container-high py-8"><div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop">
<nav class="flex items-center gap-2 text-sm text-on-surface-variant font-label-md uppercase tracking-wider mb-6">
<a href="../index.php" class="hover:text-primary transition-colors">Home</a><span class="material-symbols-outlined text-[16px]">chevron_right</span>
<a href="index.php" class="hover:text-primary transition-colors">Insights &amp; Blogs</a><span class="material-symbols-outlined text-[16px]">chevron_right</span>
<span class="text-secondary">Patient Guides</span></nav>
<h1 class="font-display-lg-mobile text-display-lg-mobile md:font-display-lg md:text-display-lg text-primary mb-6 leading-tight max-w-4xl">What Is TMJ Disorder?</h1>
<div class="flex items-center gap-6"><div class="flex items-center gap-3">
<img src="../asset/dr-navatha-mortha-facial.webp" alt="Author" class="w-10 h-10 rounded-full object-cover shadow-sm"/>
<div class="flex flex-col"><span class="text-sm font-semibold text-primary">Dr. Navatha Mortha</span>
<span class="text-xs text-on-surface-variant uppercase tracking-wider">April 5, 2026</span></div></div></div></div></div>
<div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop py-12 md:py-16">
<div class="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
<article class="lg:col-span-8">
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high mb-12">
<img alt="TMJ disorder — temporomandibular joint explained" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=tmj-disorder"/></div>
<div class="prose prose-lg prose-headings:font-headline-md prose-headings:text-primary prose-p:font-body-md prose-p:text-on-surface-variant prose-a:text-secondary prose-ul:my-6 prose-li:my-2 prose-p:my-4 prose-headings:mt-10 prose-headings:mb-4 prose-img:my-8 max-w-none">
<p class="text-xl leading-relaxed text-primary/80 font-medium italic mb-8 border-l-4 border-secondary pl-6">TMJ disorder, also called temporomandibular disorder (TMD), is a group of conditions that affect the jaw joint and the muscles that move it. It usually causes pain, clicking, or limited opening, and in most people it improves with simple self-care, medication, or a bite splint — surgery is needed only in a small minority of cases.</p>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-surface-container-high my-10 not-prose shadow-sm">
<h3 class="font-headline-sm text-[20px] text-primary mb-4 flex items-center gap-2"><span class="material-symbols-outlined text-secondary">format_list_bulleted</span>Table of Contents</h3>
<ul class="space-y-3 font-body-md text-on-surface-variant list-none p-0 m-0">
<li><a href="#what" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>What Is the TMJ?</a></li>
<li><a href="#causes" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Causes</a></li>
<li><a href="#symptoms" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Symptoms</a></li>
<li><a href="#treatment" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Treatment</a></li>
<li><a href="#faq" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Frequently Asked Questions</a></li>
</ul></div>
<h2 id="what" class="scroll-mt-24">What Is the TMJ?</h2>
<p>The temporomandibular joint (TMJ) is the paired hinge that connects your lower jaw (the mandible) to the temporal bone of the skull, just in front of each ear. You use it thousands of times a day — every time you talk, chew, yawn, or swallow. Unlike a simple door hinge, the TMJ combines a hinge movement with a sliding motion, which lets the lower jaw move forward, sideways, and open wide enough to fit food between the teeth.</p>
<p>Inside the joint sits a small, soft, oval disc made of fibrocartilage. It acts as a shock absorber between the bony surfaces and keeps the movement smooth. Around the joint, four powerful muscles of mastication — the masseter, temporalis, medial pterygoid, and lateral pterygoid — drive the jaw. When any part of this system (bone, disc, muscle, ligament, or nerve) is overloaded, inflamed, or out of alignment, the result is what clinicians call temporomandibular disorder (TMD). In everyday speech, most people simply say "TMJ".</p>
<p>Because the joint sits so close to the ear canal and shares nerve pathways with the head and neck, TMJ problems can produce symptoms far from the jaw itself — ear fullness, temple headache, even toothache. That is why many patients consult an ENT, a neurologist, or a dentist before they ever reach a maxillofacial surgeon.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10">
<img alt="Anatomy of the temporomandibular joint — bones, disc and muscles" class="w-full h-full object-cover" src="https://picsum.photos/1200/675?random=tmj-anatomy"/></div>
<h3>What "TMJ disorder" actually means</h3>
<p>TMJ disorder is not a single diagnosis. It is an umbrella term for more than thirty related conditions grouped by where the problem lies: the muscles that move the jaw (myofascial pain), the joint itself (true articular disease), or both. The most useful clinical classification, published by the International RDC/TMD Consortium Network, splits TMD into three broad groups:</p>
<ul>
<li><strong>Muscle disorders</strong> — pain and tenderness in the chewing muscles, with a normally functioning joint. The commonest form overall.</li>
<li><strong>Disc displacement disorders</strong> — the articular disc slips forward or sideways, producing clicking, locking, or limited opening. Read more in our guide on <a href="herniated-tmj-jaw-clicking-locking-or-pain-heres-what-it-really-means.php" class="font-semibold text-secondary">TMJ clicking and locking</a>.</li>
<li><strong>Arthralgia, arthritis, and arthrosis</strong> — joint inflammation (osteoarthritis, rheumatoid arthritis, or post-traumatic arthritis) and degenerative bone changes.</li>
</ul>
<p>Patients often have a mix of these. A careful clinical examination, sometimes supported by imaging, is what separates one from another — and the treatment plan is different for each.</p>
<h2 id="causes" class="scroll-mt-24">Causes</h2>
<p>TMJ disorder is usually the end result of one or more overlapping stresses on the joint and its muscles. In many patients no single cause can be blamed; the symptoms develop gradually over months or years. The most common contributors seen in our Hyderabad practice are:</p>
<p><strong>Bruxism and clenching.</strong> Night-time grinding or daytime clenching (often stress-related) overloads the disc, the joint surfaces, and the masseter and temporalis muscles. Over time the disc deforms, the joint capsule stretches, and the muscles become tender and fatigued.</p>
<p><strong>Malocclusion and jaw shape.</strong> A bad bite, an open bite, a crossbite, or a visibly asymmetric jaw changes how forces travel through the joint. Orthodontic and orthognathic problems are an under-recognised cause in young adults, and we often see symptom relief after <a href="can-braces-fix-an-asymmetrical-jaw.php" class="font-semibold text-secondary">bite correction or jaw alignment surgery</a>.</p>
<p><strong>Direct injury.</strong> A blow to the chin, a whiplash injury, intubation during surgery, or even wide-mouth dental work can tear the joint capsule or displace the disc. <a href="broken-jaw-symptoms.php" class="font-semibold text-secondary">Broken jaw injuries</a> that involve the joint surface are a recognised trigger.</p>
<p><strong>Arthritis.</strong> Osteoarthritis, rheumatoid arthritis, psoriatic arthritis, and gout can all settle in the TMJ. Degenerative change is also seen after long-standing disc displacement.</p>
<p><strong>Stress, posture, and overuse.</strong> Chronic anxiety, poor neck and head posture (especially "tech neck"), gum chewing, nail biting, and daytime jaw clenching all increase muscle load. Stress is rarely the only cause but is almost always part of the picture.</p>
<p><strong>Disc displacement.</strong> When the articular disc slips out of its normal position, the joint mechanically cannot open or close smoothly. This is the classic cause of <a href="herniated-tmj-jaw-clicking-locking-or-pain-heres-what-it-really-means.php" class="font-semibold text-secondary">TMJ clicking, catching, and locking</a>.</p>
<p><strong>Wisdom-tooth pressure and dental causes.</strong> Impacted third molars, infected teeth, and dental abscesses can refer pain into the joint and cause protective muscle spasm. See our note on <a href="can-wisdom-teeth-cause-tmj.php" class="font-semibold text-secondary">whether wisdom teeth cause TMJ</a>.</p>
<p><strong>Systemic and connective tissue disease.</strong> Ehlers-Danlos, lupus, fibromyalgia, and sleep apnoea all raise the risk of TMD.</p>
<p>Often the trigger is a combination: a small anatomical predisposition plus a period of stress plus a habit of clenching. Identifying all three is what allows a <a href="how-to-cure-tmj-permanently.php" class="font-semibold text-secondary">permanent solution</a> rather than a recurring cycle of pain.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10">
<img alt="Patient receiving TMJ examination and counselling" class="w-full h-full object-cover" src="https://picsum.photos/1200/675?random=tmj-consult"/></div>
<h2 id="symptoms" class="scroll-mt-24">Symptoms</h2>
<p>TMJ symptoms vary widely. Some patients have one dominant complaint; others have several that change with stress, posture, and time of day. The commonest patterns are:</p>
<p><strong>Joint noises.</strong> Clicking, popping, or a gravel-like grating (crepitus) when you open, close, or chew. Painless clicking is common and usually benign; clicking combined with pain or locking is not. Our guide on <a href="herniated-tmj-jaw-clicking-locking-or-pain-heres-what-it-really-means.php" class="font-semibold text-secondary">jaw clicking and locking</a> explains when to worry.</p>
<p><strong>Pain and tenderness.</strong> A dull ache in front of the ear, deep in the cheek, or over the temple is the most frequent symptom. The masseter and temporalis muscles often feel tender to press, and pain typically worsens on waking, chewing gum, or yawning wide.</p>
<p><strong>Limited or asymmetric opening.</strong> Normal mouth opening is roughly 35–55 mm (about three finger-widths). If you can no longer fit two knuckles between your front teeth, or if the jaw deviates to one side on opening, the joint or muscle is likely restricted.</p>
<p><strong>Locking.</strong> The jaw may briefly "catch" mid-open, or it may lock fully open or fully closed. Locking is uncomfortable, sometimes alarming, and almost always a sign of disc displacement.</p>
<p><strong>Headache and facial pain.</strong> TMJ disorder is one of the most overlooked causes of chronic daily headache, especially in the temple and over the eyebrow. Many patients labelled as migraine sufferers actually have myofascial TMJ pain.</p>
<p><strong>Ear symptoms.</strong> Because the joint sits right behind the ear canal, TMD can cause earache, a sense of ear fullness, ringing (tinnitus), or dizziness — often leading to repeated ENT visits before the real diagnosis is made.</p>
<p><strong>Referred pain.</strong> <a href="causes-of-jaw-pain-on-one-side.php" class="font-semibold text-secondary">One-sided jaw pain</a>, toothache without a dental cause, neck and shoulder stiffness, and even upper back tension are all common referral patterns from the masticatory muscles.</p>
<p><strong>Fatigue and sleep disturbance.</strong> Night-time clenching interrupts deep sleep and leaves the jaw feeling tired and heavy in the morning. Long-standing TMD is associated with poorer sleep quality and daytime fatigue.</p>
<p><strong>Functional limits.</strong> Difficulty biting into an apple, yawning wide, or holding the mouth open for a dental appointment are all signs that the joint is not functioning normally.</p>
<p>Track your symptoms for a week — what makes them better, what makes them worse, when they started — and bring this to your consultation. It dramatically shortens the diagnostic process.</p>
<h2 id="treatment" class="scroll-mt-24">Treatment</h2>
<p>Modern TMJ care follows a step-wise ladder. Around 80–90% of patients settle with the first two or three steps; invasive treatment is reserved for those who do not. The ladder runs from simplest and most reversible to most complex.</p>
<h3>How TMJ disorder is diagnosed</h3>
<p>A good diagnosis takes 30–45 minutes and does not usually need scans to start. Your specialist will ask about the onset of symptoms, daily habits, stress, sleep, and past injury; examine the jaw opening pattern, joint sounds, muscle tenderness, and the bite; and check the neck, ears, and cranial nerves. Imaging is added when needed — a panoramic radiograph and a CBCT scan show the bones, an MRI shows the disc and inflammation, and an ultrasound can pick up joint effusion. Blood tests are ordered when an inflammatory arthritis is suspected. The point is to confirm whether the problem is muscular, joint-based, or a mix — because the treatment plan depends on the answer.</p>
<p><strong>Step 1 — Self-care and habit change.</strong> Soft diet for two to four weeks, cutting food into small pieces, avoiding wide yawning (support the chin with a fist), applying warm compresses to relax muscles and cold packs to settle joint inflammation, and consciously keeping the teeth apart with lips together and the tongue on the palate. Habit reversal and jaw rest are surprisingly effective on their own.</p>
<p><strong>Step 2 — Medication.</strong> Short courses of anti-inflammatories (ibuprofen, naproxen, or a COX-2 inhibitor) reduce joint pain and swelling. Muscle relaxants taken at night ease clenching. Low-dose tricyclic antidepressants such as amitriptyline are useful for chronic muscular pain and for sleep. None of these are long-term answers on their own, but they buy time for the other steps to work.</p>
<p><strong>Step 3 — Physiotherapy.</strong> A trained TMJ physiotherapist uses manual therapy to release trigger points, mobilises the joint, teaches opening and posture exercises, and corrects head and neck position. A typical programme runs six to ten sessions over two to three months.</p>
<p><strong>Step 4 — Occlusal splint (bite guard).</strong> A custom-made acrylic splint worn mostly at night unloads the joint, protects the disc, and breaks the clenching habit. It is the single most common dental treatment for TMD and is backed by decades of clinical use. Learn more about <a href="how-to-cure-tmj-permanently.php" class="font-semibold text-secondary">how to cure TMJ permanently</a>.</p>
<p><strong>Step 5 — Stress, sleep, and behavioural care.</strong> Cognitive behavioural therapy, mindfulness, sleep hygiene, and treating obstructive sleep apnoea all reduce the underlying drive to clench.</p>
<p><strong>Step 6 — Injections.</strong> Botulinum toxin (Botox) injected into the masseter and temporalis relaxes overactive muscles for three to four months and is helpful for stubborn myofascial pain and hypertrophy. Intra-articular steroid or hyaluronic acid injections calm inflammation inside the joint itself.</p>
<p><strong>Step 7 — Arthrocentesis and arthroscopy.</strong> Arthrocentesis flushes the joint with sterile fluid to clear inflammatory debris and is often done for sudden closed-lock. Arthroscopy is keyhole surgery of the joint, used to wash out adhesions, reposition the disc, and treat early arthritis.</p>
<p><strong>Step 8 — Open surgery and joint replacement.</strong> Open arthrotomy, disc repair or removal, and total joint replacement with a custom-fabricated prosthetic are reserved for severe structural disease, fractures, ankylosis, or end-stage arthritis. They are successful but uncommon — fewer than 5% of TMJ patients ever need an operation.</p>
<h3>When to see a specialist</h3>
<p>Book an evaluation with a maxillofacial surgeon or a TMJ-trained dentist if any of the following apply: jaw pain lasting more than two weeks despite simple self-care; locking, catching, or inability to open the mouth fully; pain, clicking, or ear fullness that is worsening month on month; a sudden change in the bite; jaw swelling or fever; or any history of injury, arthritis, or facial trauma. <a href="broken-jaw-symptoms.php" class="font-semibold text-secondary">Broken jaw symptoms</a> and any suspicion of dislocation need urgent review. For guidance on who to see first, read our comparison of a <a href="difference-between-a-dentist-and-a-maxillofacial-surgeon.php" class="font-semibold text-secondary">dentist versus a maxillofacial surgeon</a>, or go straight to the full guide on <a href="what-type-of-doctor-do-i-need-to-see-for-tmj.php" class="font-semibold text-secondary">which doctor to consult for TMJ</a>.</p>
<p>For self-management at home, our practical guides on <a href="how-to-get-rid-of-jaw-pain-on-one-side.php" class="font-semibold text-secondary">how to relieve one-sided jaw pain</a> and on the broader <a href="what-are-the-symptoms-of-jaw-disease.php" class="font-semibold text-secondary">symptoms of jaw disease</a> are a useful next step.</p>
<div class="my-12 p-8 md:p-10 bg-gradient-to-br from-primary via-primary-container to-primary rounded-2xl border border-primary-fixed/20 text-center not-prose shadow-xl relative overflow-hidden">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.1),transparent_60%)] pointer-events-none"></div>
<span class="material-symbols-outlined text-[40px] text-secondary mb-4 relative z-10">medical_services</span>
<h3 class="font-headline-sm text-[26px] text-on-primary mb-3 relative z-10">TMJ Pain?</h3>
<p class="text-on-primary-container mb-8 relative z-10 max-w-xl mx-auto">Specialist evaluation and full range of TMJ treatments in Hyderabad.</p>
<a href="../contact.php" class="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-secondary text-on-secondary font-semibold text-sm uppercase tracking-wider hover:bg-white hover:text-primary transition-all duration-300 relative z-10 shadow-[0_0_20px_rgba(19,104,112,0.4)]">Book a Consultation<span class="material-symbols-outlined text-[18px]">arrow_forward</span></a></div>
<hr class="my-12 border-surface-container-high"/>
<h2 id="faq" class="scroll-mt-24 font-headline-md text-primary mb-6">Frequently Asked Questions</h2>
<div class="not-prose space-y-4 mb-12">
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is TMJ disorder serious?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Most cases are not serious and respond to simple care. A small number need surgery, and very rare cases need joint replacement.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Will TMJ disorder go away on its own?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Many mild cases do. Persistent or worsening symptoms need evaluation.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can TMJ cause headaches?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes — TMJ disorder is a common cause of chronic headache, especially in the temple. Many "migraines" are actually TMJ-related.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can TMJ cause ear pain?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes. The joint sits just in front of the ear canal. Many patients see an ENT first before being diagnosed with TMJ.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Do I need surgery for TMJ?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Rarely. Less than 5% of TMJ patients need surgery. Most respond to conservative care and minimally invasive procedures.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is clicking in the jaw normal?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Mild clicking without pain is common and often harmless. Clicking with pain, locking, or limited opening is not — see <a href="herniated-tmj-jaw-clicking-locking-or-pain-heres-what-it-really-means.php" class="font-semibold text-secondary">herniated TMJ disc</a>.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Does stress cause TMJ disorder?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Stress contributes through clenching and grinding. Managing stress is often part of treatment.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can a dentist treat TMJ disorder?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Mild cases yes. Severe, complex, or surgical cases need a maxillofacial surgeon. See <a href="what-type-of-doctor-do-i-need-to-see-for-tmj.php" class="font-semibold text-secondary">what type of doctor to see</a>.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is TMJ disorder permanent?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">No. Most TMJ disorders are reversible with the right combination of self-care, splint therapy, physiotherapy, and stress management. Even long-standing symptoms usually improve once the joint is unloaded and the muscles relax. The exceptions are end-stage arthritis and severe disc destruction, where joint replacement offers reliable relief. Our guide on <a href="how-to-cure-tmj-permanently.php" class="font-semibold text-secondary">how to cure TMJ permanently</a> covers this in detail.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">What happens if TMJ disorder is left untreated?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Untreated TMJ disorder can progress from intermittent clicking to persistent pain, limited mouth opening, chronic headache, and visible facial asymmetry. The disc can perforate, the joint surfaces can degenerate, and over years the bite may shift. Early treatment almost always gives a better, faster result. See <a href="what-are-the-symptoms-of-jaw-disease.php" class="font-semibold text-secondary">symptoms of jaw disease</a> for the warning signs.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Does TMJ disorder affect sleep?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes. Night-time clenching, jaw pain on waking, and the discomfort of an unstable joint all disrupt deep sleep. Many patients report waking unrefreshed, with a heavy or tired jaw. Treating the underlying TMJ problem, screening for sleep apnoea, and using a night splint together usually restore sleep quality within a few weeks.</p></details>
</div></div>
<div class="bg-surface-container-low p-8 rounded-2xl border border-surface-container-high flex flex-col md:flex-row gap-6 items-center mt-12">
<div class="w-24 h-24 rounded-full overflow-hidden shrink-0 shadow-md"><img alt="Dr. Navatha Mortha" class="w-full h-full object-cover" src="../asset/dr-navatha-mortha-facial.webp"/></div>
<div><h4 class="font-headline-sm text-lg text-primary mb-1">Dr. Navatha Mortha</h4>
<p class="font-label-md text-secondary uppercase tracking-wider mb-3 text-sm">Senior Consultant &amp; Maxillofacial Surgeon</p>
<p class="text-sm text-on-surface-variant m-0 leading-relaxed">Dr. Mortha manages the full range of TMJ disorders at Gnathos Facial Surgery, Hyderabad, from conservative care to arthroscopy and joint replacement.</p></div></div>
</article>
<aside class="lg:col-span-4 space-y-12">
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-4">Search Journal</h3>
<div class="relative"><input type="text" placeholder="Search articles..." class="w-full pl-4 pr-10 py-3 rounded-xl border border-surface-container-high bg-surface text-sm focus:outline-none focus:ring-2 focus:ring-secondary focus:border-transparent"/>
<span class="material-symbols-outlined absolute right-3 top-1/2 -translate-y-1/2 text-on-surface-variant">search</span></div></div>
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-4">Categories</h3>
<ul class="space-y-3 font-body-md text-on-surface-variant">
<li class="flex items-center justify-between group cursor-pointer"><a href="#" class="group-hover:text-secondary transition-colors">Patient Guides</a><span class="text-xs bg-surface-container-low px-2 py-1 rounded">8</span></li>
</ul></div>
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-6">Related Articles</h3>
<div class="space-y-6 flex flex-col">
<div class="group cursor-pointer"><a href="how-to-cure-tmj-permanently.php" class="block">
<span class="text-xs font-semibold text-secondary uppercase tracking-wider mb-1 block">Patient Guides</span>
<h4 class="font-headline-sm text-lg text-primary leading-snug group-hover:text-secondary transition-colors">How to Cure TMJ Permanently</h4>
</a></div>
<div class="group cursor-pointer"><a href="herniated-tmj-jaw-clicking-locking-or-pain-heres-what-it-really-means.php" class="block">
<span class="text-xs font-semibold text-secondary uppercase tracking-wider mb-1 block">Patient Guides</span>
<h4 class="font-headline-sm text-lg text-primary leading-snug group-hover:text-secondary transition-colors">Herniated TMJ Disc</h4>
</a></div>
</div></div>
<div class="bg-primary text-on-primary p-8 rounded-2xl shadow-lg relative overflow-hidden text-center sticky top-24">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.1),transparent_70%)] pointer-events-none"></div>
<span class="material-symbols-outlined text-[48px] text-secondary mb-4">medical_services</span>
<h3 class="font-headline-sm text-2xl mb-3">TMJ Pain?</h3>
<p class="text-on-primary-container text-sm mb-6">Full range of treatments in Hyderabad.</p>
<a href="../contact.php" class="inline-block w-full py-3 rounded-xl bg-secondary hover:bg-secondary/90 transition-colors text-on-secondary font-semibold text-sm uppercase tracking-wider">Book Now</a>
</div></aside></div></div>
</main>
<?php
include $path_prefix . 'footer.php';
?>