<?php
$path_prefix = "../";
$page_title = "What Are the Symptoms of Jaw Disease? | Gnathos Facial Surgery";
$page_description = "Jaw disease covers a wide range of conditions — infections, cysts, tumours, arthritis, and more. Learn the symptoms that should prompt evaluation.";
$page_keywords = "symptoms of jaw disease, jaw disease signs, jaw bone disease symptoms, jaw cyst symptoms, jaw tumour symptoms";
$canonical_url = "https://gnathosface.com/blogs/what-are-the-symptoms-of-jaw-disease/";
include $path_prefix . 'header-include.php';
include $path_prefix . 'header.php';
?>
<link href="/blogs/blog-style.css" rel="stylesheet">
<main>
<div class="bg-surface-container-low border-b border-surface-container-high py-8"><div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop">
<nav class="flex items-center gap-2 text-sm text-on-surface-variant font-label-md uppercase tracking-wider mb-6">
<a href="../index.php" class="hover:text-primary transition-colors">Home</a><span class="material-symbols-outlined text-[16px]">chevron_right</span>
<a href="index.php" class="hover:text-primary transition-colors">Insights &amp; Blogs</a><span class="material-symbols-outlined text-[16px]">chevron_right</span>
<span class="text-secondary">Patient Guides</span></nav>
<h1 class="font-display-lg-mobile text-display-lg-mobile md:font-display-lg md:text-display-lg text-primary mb-6 leading-tight max-w-4xl">What Are the Symptoms of Jaw Disease?</h1>
<div class="flex items-center gap-6"><div class="flex items-center gap-3">
<img src="/asset/dr-navatha-mortha-facial.webp" alt="Author" class="w-10 h-10 rounded-full object-cover shadow-sm"/>
<div class="flex flex-col"><span class="text-sm font-semibold text-primary">Dr. Navatha Mortha</span>
<span class="text-xs text-on-surface-variant uppercase tracking-wider">April 6, 2026</span></div></div></div></div></div>
<div class="max-w-container-max mx-auto px-margin-mobile md:px-margin-desktop py-12 md:py-16">
<div class="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-16">
<article class="lg:col-span-8">
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high mb-12">
<img alt="Symptoms of jaw disease — overview of warning signs" class="w-full h-full object-cover" src="https://picsum.photos/1200/600?random=jaw-disease"/></div>
<div class="prose prose-lg prose-headings:font-headline-md prose-headings:text-primary prose-p:font-body-md prose-p:text-on-surface-variant prose-a:text-secondary prose-ul:my-6 prose-li:my-2 prose-p:my-4 prose-headings:mt-10 prose-headings:mb-4 prose-img:my-8 max-w-none">
<p class="text-xl leading-relaxed text-primary/80 font-medium italic mb-8 border-l-4 border-secondary pl-6">Jaw disease is a broad medical term covering infections, cysts, tumours, arthritis, metabolic bone disorders, and trauma-related conditions affecting the jaw bones, joints, and surrounding soft tissues. The most common symptoms are jaw or facial pain, swelling, stiffness, clicking or locking of the jaw joint, and changes in how your teeth fit together. If you notice any of these signs — especially a lump, numbness, or pain that lasts more than two weeks — see a maxillofacial surgeon promptly for evaluation.</p>
<div class="bg-surface-container-lowest p-6 rounded-xl border border-surface-container-high my-10 not-prose shadow-sm">
<h3 class="font-headline-sm text-[20px] text-primary mb-4 flex items-center gap-2"><span class="material-symbols-outlined text-secondary">format_list_bulleted</span>Table of Contents</h3>
<ul class="space-y-3 font-body-md text-on-surface-variant list-none p-0 m-0">
<li><a href="#types" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>What "Jaw Disease" Actually Means</a></li>
<li><a href="#common" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>General Symptoms</a></li>
<li><a href="#serious" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Red-Flag Symptoms</a></li>
<li><a href="#diagnosis" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>How It's Diagnosed</a></li>
<li><a href="#treatment" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Treatment Overview</a></li>
<li><a href="#when" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>When to See a Surgeon</a></li>
<li><a href="#faq" class="hover:text-secondary transition-colors flex items-center gap-2"><span class="material-symbols-outlined text-[16px] text-secondary">arrow_right</span>Frequently Asked Questions</a></li>
</ul></div>
<h2 id="types" class="scroll-mt-24">What "Jaw Disease" Actually Means</h2>
<p>"Jaw disease" is not one diagnosis. It is a catch-all phrase used by patients and clinicians for any abnormal process affecting the mandible (lower jaw), maxilla (upper jaw), the temporomandibular joints (TMJs), or the muscles and nerves that move them. The category includes inflammatory conditions, infections, cysts, benign and malignant tumours, arthritis, metabolic bone disorders, and the aftermath of trauma. Some are common and self-limiting; others are rare but life-threatening. Because the early symptoms overlap heavily — pain, swelling, stiffness — any persistent jaw complaint deserves a proper evaluation.</p>
<p>For convenience, jaw diseases are usually grouped into seven main families. Understanding which family your symptoms fall into helps your surgeon decide which imaging, blood tests, or biopsy you need first.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10">
<img alt="Anatomical illustration of the jaw joint and surrounding bone" class="w-full h-full object-cover" src="https://picsum.photos/1200/675?random=jaw-anatomy"/></div>
<h3 id="infection" class="scroll-mt-24">Infection</h3>
<p>Bacterial infection of the jaw is one of the most common jaw diseases. It usually starts as a dental abscess from an untreated cavity, a cracked tooth, or a failed <a href="symptoms-of-jaw-infection-after-the-root-canal.php" class="font-semibold text-secondary">root canal</a>. If the infection spreads into the bone itself, it becomes osteomyelitis — a serious condition that may need weeks of antibiotics and sometimes surgical debridement. Symptoms include throbbing pain, fever, facial swelling, a bad taste, and sometimes difficulty opening the mouth.</p>
<h3 id="cysts" class="scroll-mt-24">Cysts</h3>
<p>Jaw cysts are fluid- or air-filled sacs lined by epithelium that grow slowly inside the bone. Common types include dentigerous cysts (around the crown of an unerupted tooth — see <a href="symptoms-of-impacted-wisdom-tooth.php" class="font-semibold text-secondary">impacted wisdom tooth symptoms</a>), radicular cysts at the tip of a dead tooth, and odontogenic keratocysts, which have a high recurrence rate. Most cysts are benign but they quietly destroy bone, push teeth out of position, and can fracture the jaw if left alone for years.</p>
<h3 id="tumours" class="scroll-mt-24">Benign and Malignant Tumours</h3>
<p>Benign jaw tumours like ameloblastoma, odontoma, and central giant cell granuloma grow locally but do not spread to other organs. Malignant tumours include oral squamous cell carcinoma (see <a href="what-are-the-symptoms-of-oral-cancer.php" class="font-semibold text-secondary">oral cancer symptoms</a>), osteosarcoma of the jaw, and metastatic deposits from cancers of the breast, kidney, prostate, or lung. Malignant lesions tend to grow faster, cause numbness, and loosen teeth without gum disease.</p>
<h3 id="arthritis" class="scroll-mt-24">Arthritis of the TMJ</h3>
<p>The temporomandibular joint can develop osteoarthritis (wear-and-tear), rheumatoid arthritis (autoimmune), psoriatic arthritis, or post-traumatic arthritis after an injury. Each behaves slightly differently but the symptoms overlap with <a href="what-is-tmj-disorder.php" class="font-semibold text-secondary">TMJ disorder</a> — pain on chewing, joint noises, morning stiffness, and reduced opening. A <a href="herniated-tmj-jaw-clicking-locking-or-pain-heres-what-it-really-means.php" class="font-semibold text-secondary">herniated TMJ disc</a> is closely related and can be the first sign of underlying arthritic change.</p>
<h3 id="necrosis" class="scroll-mt-24">Osteonecrosis and Medication-Related Damage</h3>
<p>Bisphosphonate-related osteonecrosis of the jaw (BRONJ) and radiation-related osteonecrosis (ORN) occur when bone in the jaw fails to heal after minor injury or dental work. They are seen in patients on long-term osteoporosis drugs or those who have had head-and-neck radiotherapy. Exposed bone, non-healing extraction sockets, and chronic infection are the hallmarks.</p>
<h3 id="trauma" class="scroll-mt-24">Trauma and Fractures</h3>
<p>A direct blow to the face — from a fall, road accident, or sports injury — can fracture the mandible, maxilla, or both. Symptoms include misalignment of the teeth, inability to close the mouth properly, numbness of the lower lip, and bleeding inside the ear. See <a href="broken-jaw-symptoms.php" class="font-semibold text-secondary">broken jaw symptoms</a> for a fuller list and <a href="emergency-treatment-for-facial-injuries-near-hyderbaad.php" class="font-semibold text-secondary">emergency treatment for facial injuries near Hyderabad</a> for first-aid guidance.</p>
<h3 id="metabolic" class="scroll-mt-24">Metabolic, Congenital, and Salivary Disorders</h3>
<p>Osteoporosis, Paget's disease of bone, and rare conditions like cherubism can change the shape, density, or size of the jaws. Salivary gland obstruction or tumours in the parotid and submandibular glands present as swellings near the jaw angle and are sometimes mistaken for jaw disease itself. Congenital asymmetries of jaw growth are covered under <a href="causes-of-facial-asymmetry-common-medical-dental-and-structural-reasons.php" class="font-semibold text-secondary">causes of facial asymmetry</a>.</p>
<h2 id="common" class="scroll-mt-24">General Symptoms of Jaw Disease</h2>
<p>Most jaw diseases — whether inflammatory, infectious, or neoplastic — share a small set of warning signs. The challenge is that these signs are usually mild at first and easy to dismiss as stress, a cold, or a toothache. Tracking how long they have lasted and whether they are getting worse is often more useful than the symptom itself.</p>
<p><strong>Pain.</strong> Pain is the most common reason patients seek help. It can be a dull, constant ache in the jaw bone, a sharp stab on biting, or a deep earache with no ear problem. Pain that wakes you at night, radiates to the temple, or is triggered by chewing deserves evaluation. Unilateral jaw pain is covered in detail under <a href="causes-of-jaw-pain-on-one-side.php" class="font-semibold text-secondary">causes of jaw pain on one side</a>.</p>
<p><strong>Swelling.</strong> New or growing swelling of the jaw, face, or neck is never normal. It may be firm and bony (suggesting a cyst or tumour), soft and tender (suggesting an abscess), or diffuse and rubbery (suggesting inflammation). Any lump that persists for more than two weeks needs imaging.</p>
<p><strong>Stiffness and limited opening.</strong> A normal adult can open the mouth 35–55 mm (about three finger-widths). If you cannot fit two fingers between your front teeth, you have trismus. It can come from joint arthritis, muscle spasm, an infection near the jaw muscles, or a tumour blocking jaw movement.</p>
<p><strong>Joint noises.</strong> Clicking, popping, or grating sounds in the TMJ are extremely common and often harmless. They become significant when paired with pain, locking, or reduced opening. Read more in <a href="herniated-tmj-jaw-clicking-locking-or-pain-heres-what-it-really-means.php" class="font-semibold text-secondary">herniated TMJ disc — clicking, locking, or pain</a> and <a href="what-is-tmj-disorder.php" class="font-semibold text-secondary">what is TMJ disorder</a>.</p>
<p><strong>Malocclusion.</strong> A sudden change in the way your teeth fit together — a new gap, a tooth that suddenly feels "high," or a bite that has shifted — can signal a fracture, a tumour displacing the bone, or advanced joint arthritis.</p>
<p><strong>Loose teeth without gum disease.</strong> If your gums look healthy but a tooth is becoming loose, the supporting bone may be eroded by a cyst, tumour, or osteomyelitis.</p>
<p><strong>Numbness.</strong> Tingling, pins-and-needles, or complete numbness of the lower lip, chin, or tongue suggests that the inferior alveolar or lingual nerve is being compressed or invaded. This is a red-flag symptom (see below).</p>
<p><strong>Headache, earache, and facial fullness.</strong> Jaw disease often mimics ENT problems. Referred pain from the TMJ or masseter muscle is a common cause of morning headache and a feeling of blocked ears.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10">
<img alt="Patient pointing to the side of the face, indicating jaw pain location" class="w-full h-full object-cover" src="https://picsum.photos/1200/675?random=jaw-pain-location"/></div>
<h3 id="specific" class="scroll-mt-24">Disease-Specific Symptoms</h3>
<p>Some patterns point strongly to a particular diagnosis. Use these as a guide — not a diagnosis — when you speak to your surgeon.</p>
<ul>
<li><strong>TMJ osteoarthritis:</strong> grating sound (crepitus) on opening, morning stiffness under 30 minutes, pain on chewing tough food.</li>
<li><strong>Rheumatoid arthritis of the TMJ:</strong> bilateral jaw stiffness worse in the morning, often with finger or wrist joint pain, and a gradually receding chin in long-standing cases.</li>
<li><strong>Jaw osteomyelitis:</strong> deep, boring pain, fever, facial swelling, a draining sinus on the skin or inside the mouth, and often a recent dental infection or extraction.</li>
<li><strong>Dentigerous cyst or odontogenic keratocyst:</strong> painless slow swelling of the jaw, delayed tooth eruption, or a missing tooth that has not come in by the expected age.</li>
<li><strong>Ameloblastoma:</strong> a firm, painless, slowly expanding swelling of the lower jaw (mandible), most often in adults aged 30–50.</li>
<li><strong>Oral cancer:</strong> a non-healing ulcer, red or white patch, or mass inside the mouth lasting more than 2 weeks — see <a href="what-are-the-symptoms-of-oral-cancer.php" class="font-semibold text-secondary">symptoms of oral cancer</a>.</li>
<li><strong>Osteonecrosis of the jaw:</strong> exposed yellow-white bone visible inside the mouth, usually after dental extraction, in a patient on bisphosphonates or after radiotherapy.</li>
<li><strong>Salivary gland obstruction:</strong> painful swelling under the jaw angle or in front of the ear that worsens with eating.</li>
</ul>
<h2 id="serious" class="scroll-mt-24">Red-Flag Symptoms That Need Urgent Care</h2>
<p>Some jaw symptoms should never be watched and waited. They are red flags because they point to conditions that get worse quickly — aggressive infections, malignancy, or nerve involvement. If you have any of the following, book an urgent appointment with a maxillofacial surgeon or visit an emergency department the same day.</p>
<p><strong>A new lump or mass in the jaw, mouth, or neck.</strong> Any mass that grows over weeks, feels hard, is fixed to deeper tissue, or measures more than 1.5 cm needs imaging and usually a biopsy. A persistent neck node larger than 1 cm is the classic presentation of head-and-neck cancer spreading to lymph nodes.</p>
<p><strong>A sore in the mouth that does not heal in 2 weeks.</strong> The single most important red flag for oral cancer. Any ulcer, crack, or area of redness that has not resolved within 14 days — even if it is painless — must be examined. See <a href="what-are-the-symptoms-of-oral-cancer.php" class="font-semibold text-secondary">symptoms of oral cancer</a> for the full list of warning signs.</p>
<p><strong>Numbness of the tongue, lip, or chin.</strong> Sudden or progressive numbness, especially on one side, suggests that a lesion is pressing on or invading the inferior alveolar, lingual, or mental nerve. Combined with pain and a lump, it strongly suggests malignancy.</p>
<p><strong>Difficulty opening the mouth (trismus).</strong> An inter-incisal distance under 25 mm limits eating, brushing, and dental care. Sudden trismus with fever suggests a peritonsillar or pterygomandibular space abscess — a surgical emergency.</p>
<p><strong>Difficulty swallowing, speaking, or moving the tongue.</strong> These suggest that a tumour is encroaching on the floor of the mouth, tongue base, or oropharynx. Unexplained hoarseness lasting more than 3 weeks also needs a throat examination.</p>
<p><strong>Unexplained weight loss, night sweats, or persistent fatigue.</strong> These systemic signs combined with any jaw symptom point toward malignancy or chronic infection such as tuberculosis or osteomyelitis of the jaw.</p>
<p><strong>Persistent pain that does not respond to routine treatment.</strong> If pain has lasted more than 4 weeks despite painkillers, antibiotics, or splint therapy, you need imaging — not a stronger prescription.</p>
<p><strong>Bleeding from a growth, socket, or nose.</strong> Spontaneous bleeding or blood-tinged saliva from a mass or non-healing extraction socket is a red-flag sign that warrants urgent biopsy and imaging.</p>
<h2 id="diagnosis" class="scroll-mt-24">How Jaw Disease Is Diagnosed</h2>
<p>Diagnosis follows a four-step pathway: history, clinical examination, imaging, and tissue or blood confirmation when needed. Each step narrows the possibilities until one diagnosis fits best.</p>
<h3 class="scroll-mt-24">Clinical examination</h3>
<p>The first consultation is the most important. Your surgeon will ask how long symptoms have lasted, what makes them worse, and whether you have had recent dental work, infections, trauma, or systemic illness. They will then palpate the TMJs, masseter and temporalis muscles, lymph nodes of the neck, and the floor of the mouth. Mouth opening is measured in millimetres, the bite is checked for changes, and the nerves supplying the lip, chin, and tongue are tested with light touch and pin-prick. A properly done clinical exam often short-circuits the need for advanced imaging.</p>
<h3 class="scroll-mt-24">Imaging</h3>
<p>An <strong>OPG (orthopantomogram)</strong> is the standard panoramic X-ray of both jaws and is usually the first scan ordered. It is cheap, quick, and excellent for showing teeth, fractures, large cysts, and obvious bone destruction. A <strong>CBCT (cone-beam CT)</strong> gives a 3-D view of the jaw bones and is essential before any surgery on cysts or tumours. A <strong>medical CT scan with contrast</strong> is preferred for malignant lesions and head-and-neck emergencies. <strong>MRI</strong> is the scan of choice for the TMJ disc, soft-tissue tumours, salivary glands, and the bone marrow in osteomyelitis. <strong>Ultrasound</strong> is useful for salivary glands and neck lymph nodes.</p>
<div class="aspect-[16/9] w-full rounded-2xl overflow-hidden shadow-lg border border-surface-container-high my-10">
<img alt="Dental panoramic X-ray of the jaws and teeth" class="w-full h-full object-cover" src="https://picsum.photos/1200/675?random=jaw-xray-opg"/></div>
<h3 class="scroll-mt-24">Biopsy</h3>
<p>Any mass that does not have a clear, benign explanation should be biopsied. For lesions inside the bone, an incisional biopsy under local or general anaesthesia is standard. For suspicious oral ulcers, a punch or scalpel biopsy of the edge of the lesion is sent for histopathology. The result — usually within 5–7 days — guides whether further surgery, oncology referral, or simple observation is needed.</p>
<h3 class="scroll-mt-24">Blood tests</h3>
<p>Blood work helps when infection, inflammation, or metabolic disease is suspected. A complete blood count, ESR, CRP, rheumatoid factor, anti-CCP, calcium, vitamin D, alkaline phosphatase, and uric acid are commonly requested. For salivary disease, amylase and autoimmune panels (SSA/SSB) may be added.</p>
<p>Early diagnosis is the single biggest factor in outcome — especially for infections and tumours. For emergencies, see <a href="emergency-treatment-for-facial-injuries-near-hyderbaad.php" class="font-semibold text-secondary">emergency treatment for facial injuries near Hyderabad</a>.</p>
<h2 id="treatment" class="scroll-mt-24">Treatment Overview</h2>
<p>Treatment depends on the specific diagnosis, the size and location of the lesion, and your overall health. The four broad categories are:</p>
<p><strong>Medication.</strong> Most infections resolve with targeted antibiotics, drainage, and removal of the source tooth. Arthritic pain is managed with NSAIDs, muscle relaxants, a soft diet, jaw exercises, and occlusal splints. Bisphosphonate-related osteonecrosis may need antibiotics, antimicrobial mouth rinses, and a pause in the offending drug after discussion with your physician.</p>
<p><strong>Minimally invasive procedures.</strong> Small cysts can be marsupialised (opened and left to shrink), large joint effusions can be aspirated, and TMJ inflammation can be managed with arthrocentesis or arthroscopy. These are usually day-care procedures under local anaesthesia or short general anaesthesia.</p>
<p><strong>Surgery.</strong> Definitive treatment for most cysts, benign tumours, fractures, and malignancies. Enucleation, curettage, segmental resection with bone reconstruction (using bone grafts or vascularised free flaps), and fracture fixation with miniplates are all standard. Your surgeon will discuss the approach, expected downtime, and any need for <a href="difference-between-a-dentist-and-a-maxillofacial-surgeon.php" class="font-semibold text-secondary">orthognathic</a> or reconstructive work.</p>
<p><strong>Oncology referral.</strong> Malignant tumours are managed jointly with head-and-neck oncology, with surgery, radiotherapy, chemotherapy, or a combination. Early-stage oral cancer has a 5-year survival above 80 percent; late-stage disease drops below 40 percent — which is why early evaluation matters.</p>
<h2 id="when" class="scroll-mt-24">When to See a Maxillofacial Surgeon</h2>
<p>See a maxillofacial surgeon — not just a general dentist — if you have any of the following: persistent jaw or facial pain lasting more than 2 weeks; a lump anywhere in the jaw, mouth, or neck; numbness of the lip, chin, or tongue; sudden change in bite; inability to open the mouth more than two finger-widths; repeated jaw locking; or any non-healing mouth ulcer. A maxillofacial surgeon is trained in both the medical and surgical management of these conditions. To choose the right specialist, see <a href="what-type-of-doctor-do-i-need-to-see-for-tmj.php" class="font-semibold text-secondary">what type of doctor you need to see for TMJ</a> and the difference between <a href="difference-between-a-dentist-and-a-maxillofacial-surgeon.php" class="font-semibold text-secondary">a dentist and a maxillofacial surgeon</a>.</p>
<div class="my-12 p-8 md:p-10 bg-gradient-to-br from-primary via-primary-container to-primary rounded-2xl border border-primary-fixed/20 text-center not-prose shadow-xl relative overflow-hidden">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.1),transparent_60%)] pointer-events-none"></div>
<span class="material-symbols-outlined text-[40px] text-secondary mb-4 relative z-10">medical_services</span>
<h3 class="font-headline-sm text-[26px] text-on-primary mb-3 relative z-10">Any Jaw Symptom That Worries You?</h3>
<p class="text-on-primary-container mb-8 relative z-10 max-w-xl mx-auto">Specialist evaluation, imaging, and biopsy in Hyderabad.</p>
<a href="../contact.php" class="inline-flex items-center gap-2 px-8 py-4 rounded-xl bg-secondary text-on-secondary font-semibold text-sm uppercase tracking-wider hover:bg-white hover:text-primary transition-all duration-300 relative z-10 shadow-[0_0_20px_rgba(19,104,112,0.4)]">Book a Consultation<span class="material-symbols-outlined text-[18px]">arrow_forward</span></a></div>
<hr class="my-12 border-surface-container-high"/>
<h2 id="faq" class="scroll-mt-24 font-headline-md text-primary mb-6">Frequently Asked Questions</h2>
<div class="not-prose space-y-4 mb-12">
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can jaw disease be cancer?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Some jaw diseases are malignant. Most jaw swellings are benign, but any new mass or persistent symptom needs evaluation. See <a href="what-are-the-symptoms-of-oral-cancer.php" class="font-semibold text-secondary">oral cancer symptoms</a>.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">How do I know if my jaw pain is serious?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Any jaw pain that lasts more than 2 weeks, doesn't respond to routine treatment, or comes with swelling, numbness, or a lump should be evaluated.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">What doctor treats jaw disease?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">A maxillofacial surgeon. See <a href="what-type-of-doctor-do-i-need-to-see-for-tmj.php" class="font-semibold text-secondary">what type of doctor to see</a> and <a href="difference-between-a-dentist-and-a-maxillofacial-surgeon.php" class="font-semibold text-secondary">dentist vs maxillofacial surgeon</a>.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Are jaw cysts dangerous?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Most cysts are benign but they grow silently, displace teeth, weaken bone, and can get infected. They are usually removed or enucleated.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can jaw disease cause facial swelling?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes — infections, cysts, and tumours all cause swelling. New or growing swelling should always be evaluated.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">What imaging is best for jaw disease?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">An OPG is a good first step. A CBCT (3D scan) gives much more detail. MRI is best for soft tissue and joints.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Is jaw disease hereditary?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Some forms are — ameloblastoma, certain cysts, and some arthritic conditions. Family history is relevant.</p></details>
<details class="group border border-surface-container-high rounded-xl bg-surface-container-lowest p-6 cursor-pointer open:bg-surface-container-low transition-colors shadow-sm"><summary class="font-headline-sm text-primary text-[18px] flex justify-between items-center list-none font-semibold">Can jaw disease affect my teeth?<span class="material-symbols-outlined group-open:rotate-180 transition-transform text-secondary">expand_more</span></summary><p class="mt-4 font-body-md text-on-surface-variant leading-relaxed">Yes. Cysts and tumours can displace or loosen teeth. Infections can spread to teeth and vice versa.</p></details>
</div></div>
<div class="bg-surface-container-low p-8 rounded-2xl border border-surface-container-high flex flex-col md:flex-row gap-6 items-center mt-12">
<div class="w-24 h-24 rounded-full overflow-hidden shrink-0 shadow-md"><img alt="Dr. Navatha Mortha" class="w-full h-full object-cover" src="/asset/dr-navatha-mortha-facial.webp"/></div>
<div><h4 class="font-headline-sm text-lg text-primary mb-1">Dr. Navatha Mortha</h4>
<p class="font-label-md text-secondary uppercase tracking-wider mb-3 text-sm">Senior Consultant &amp; Maxillofacial Surgeon</p>
<p class="text-sm text-on-surface-variant m-0 leading-relaxed">Dr. Mortha evaluates and treats the full range of jaw disease at Gnathos Facial Surgery, Hyderabad, working with pathologists and oncologists when needed.</p></div></div>
</article>
<aside class="lg:col-span-4 space-y-12">
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-4">Search Journal</h3>
<div class="relative"><input type="text" placeholder="Search articles..." class="w-full pl-4 pr-10 py-3 rounded-xl border border-surface-container-high bg-surface text-sm focus:outline-none focus:ring-2 focus:ring-secondary focus:border-transparent"/>
<span class="material-symbols-outlined absolute right-3 top-1/2 -translate-y-1/2 text-on-surface-variant">search</span></div></div>
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-4">Categories</h3>
<ul class="space-y-3 font-body-md text-on-surface-variant">
<li class="flex items-center justify-between group cursor-pointer"><a href="#" class="group-hover:text-secondary transition-colors">Patient Guides</a><span class="text-xs bg-surface-container-low px-2 py-1 rounded">8</span></li>
</ul></div>
<div class="bg-surface-container-lowest p-6 rounded-2xl shadow-sm border border-surface-container-high">
<h3 class="font-headline-sm text-xl text-primary mb-6">Related Articles</h3>
<div class="space-y-6 flex flex-col">
<div class="group cursor-pointer"><a href="what-are-the-symptoms-of-oral-cancer.php" class="block">
<span class="text-xs font-semibold text-secondary uppercase tracking-wider mb-1 block">Patient Guides</span>
<h4 class="font-headline-sm text-lg text-primary leading-snug group-hover:text-secondary transition-colors">What Are the Symptoms of Oral Cancer?</h4>
</a></div>
<div class="group cursor-pointer"><a href="symptoms-of-jaw-infection-after-the-root-canal.php" class="block">
<span class="text-xs font-semibold text-secondary uppercase tracking-wider mb-1 block">Patient Guides</span>
<h4 class="font-headline-sm text-lg text-primary leading-snug group-hover:text-secondary transition-colors">Symptoms of Jaw Infection After Root Canal</h4>
</a></div>
</div></div>
<div class="bg-primary text-on-primary p-8 rounded-2xl shadow-lg relative overflow-hidden text-center sticky top-24">
<div class="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(255,255,255,0.1),transparent_70%)] pointer-events-none"></div>
<span class="material-symbols-outlined text-[48px] text-secondary mb-4">medical_services</span>
<h3 class="font-headline-sm text-2xl mb-3">Jaw Symptom?</h3>
<p class="text-on-primary-container text-sm mb-6">Specialist evaluation in Hyderabad.</p>
<a href="../contact.php" class="inline-block w-full py-3 rounded-xl bg-secondary hover:bg-secondary/90 transition-colors text-on-secondary font-semibold text-sm uppercase tracking-wider">Book Now</a>
</div></aside></div></div>
</main>
<?php
include $path_prefix . 'footer.php';
?>